---
clusterInfo: {}

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.82.0"
  pullPolicy: IfNotPresent

resources: {}

memory_limiter:
  limit_mib: "400"
  spike_limit_mib: "100"
  check_interval: "5s"

memory_ballast:
  enabled: true
  size_mib: 683

spanmetrics_exporter:
  enabled: false
  # endpoint: spanmetrics-collector:4317

# override in downstream parent chart to deploy ServiceMonitor
# allows Prometheus Operator to scrape metrics
servicemonitor:
  enabled: false

# including additional attributes requires creating _otel-attributes.tpl in application chart
# see README for an example
include_otel_attributes: false
