---
clusterInfo: {}

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.42.0"
  pullPolicy: IfNotPresent

resources: {}


otel_collector:
  memory_limiter:
    limit_mib: "400"
    spike_limit_mib: "100"
    check_interval: "5s"
