---
clusterInfo: {}

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.100.0"
  pullPolicy: IfNotPresent

resources: {}

memory_limiter:
  limit_mib: "400"
  spike_limit_mib: "100"
  check_interval: "5s"

memory_ballast:
  enabled: true
  size_mib: 683

# allow exporting to an additional collector or tracing backend
addl_traces_exporter:
  enabled: false
  # name: otlp/spanmetrics
  # endpoint: spanmetrics-collector:4317
  # tls: "insecure: true"

# override in downstream parent chart to deploy ServiceMonitor
# allows Prometheus Operator to scrape metrics
servicemonitor:
  enabled: false

# including additional attributes requires creating _otel-attributes.tpl in application chart
# see README for an example
include_otel_attributes: false
