apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
data:
  opentelemetry-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:55681
    processors:
      batch:
        timeout: 100s
      memory_limiter:
        limit_mib: "400"
        spike_limit_mib: "100"
        check_interval: "5s"
      resource:
        attributes:
        - key: k8s.cluster.endpoint
          value: {{ .Values.clusterInfo.apiEndpoint }}
          action: insert
        - key: k8s.cluster.class
          value: {{ .Values.clusterInfo.class }}
          action: insert
        - key: k8s.cluster.fqdn
          value: {{ .Values.clusterInfo.fqdn }}
          action: insert
        - key: k8s.cluster.name
          value: {{ .Values.clusterInfo.name }}
          action: insert
        - key: metal.facility
          value: {{ .Values.clusterInfo.facility }}
          action: insert
    exporters:
      otlp:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "${HONEYCOMB_TEAM}"
          "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      zpages:
      memory_ballast:
        size_mib: 683
    service:
      extensions: [memory_ballast, health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [otlp]
