apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
data:
  opentelemetry-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:55681
      prometheus:
        config:
          scrape_configs:
            - job_name: {{ .Release.Namespace }}-collector
              scrape_interval: 15s
              static_configs:
                - targets: ["127.0.0.1:8888"]

    processors:
      batch:
        timeout: 200ms
      memory_limiter:
        limit_mib: {{ .Values.memory_limiter.limit_mib }}
        spike_limit_mib: {{ .Values.memory_limiter.spike_limit_mib }}
        check_interval: {{ .Values.memory_limiter.check_interval }}
      resource:
        attributes:{{ if .Values.include_otel_attributes }}{{- include "otel_attributes" . | indent 8 }}{{ end }}
        - key: service.group
          value: "equinix-metal"
          action: insert

    exporters:
      otlp:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "${HONEYCOMB_ENV_API_KEY}"
      otlp/metrics:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "${HONEYCOMB_ENV_API_KEY}"
          # dataset is required for metrics data
          "x-honeycomb-dataset": "collector-metrics"
      prometheus:
        endpoint: "0.0.0.0:9090"

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [2ms, 4ms, 6ms, 8ms, 10ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1s, 1400ms, 2s, 5s, 10s, 15s]
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
        exclude_dimensions: ['status.code']
        dimensions_cache_size: 1000
        aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
        metrics_flush_interval: 15s

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      zpages:
      memory_ballast:
        size_mib: 683

    service:
      extensions: [memory_ballast, health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [prometheus]
          processors: [resource]
          exporters: [otlp/metrics]
        metrics/spanmetrics:
          receivers: [spanmetrics]
          processors: []
          exporters: [prometheus]
