apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
spec:
  sessionAffinity: None
  type: ClusterIP
  selector:
    k8s-app: opentelemetry-collector
  ports:
  - name: otlp
    port: 55680
    protocol: TCP
    targetPort: otlp
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: otlp-grpc
  - name: otlp-http
    port: 55681
    protocol: TCP
    targetPort: otlp-http
  - name: prometheus-collector-metrics
    port: 8888
    protocol: TCP
    targetPort: 8888


{{ if .Values.servicemonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opentelemetry-collector-servicemonitor
  labels:
    app: opentelemetry-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  endpoints:
  - port: prometheus-collector-metrics
    interval: 15s
{{ end }}
