name: Yaml Lint
on: [pull_request]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prep helm
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm template --output-dir test-output/ .
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: test-output
        config_file: .yamllint.yml
